### ISSUE TITLE
add DRAFT watermark to Dev version?

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#21]
This will be helpful when sharing with alpha testers

**Comment by dpritchLibre** [comment]
I'm not sure that I feel like staring at a watermark from now until eternity.  Maybe check out a branch from develop that adds the watermark and just merge develop into that branch periodically?

This raises another point: we probably should add a date somewhere to the document so that readers who have a pdf or printout can look and see how current their version is.  Maybe a single date on the front page, e.g. **last updated \date**.  Or another way would be to include it in the footer on every page.

**Comment by BarkleyBG** [comment]
migrating to #22, and marking this as a duplicate

**Comment by BarkleyBG** [comment]
Closing this for now. We may revisit when we are ready to share the document
