### ISSUE TITLE
How to tailor document to many setups? with a consistent style?

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#32]
Readers might be using Mac/Windows/Linux, R/Rstudio/Emacs, or any number of SSH clients. I think we should refer to them as "Local machine" (or perhaps "laptop" just for simplicity), "R GUI", and "SSH Client". for clarity.

There are times when the difference between these options is not-insignificant and, pragmatically, we should address certain option-specific issues. E.g., windows pathnames are an evergreen issue. We should always make reference to these option-specific issues in a consistent style.

Sub-sub-sections is appealing but may run into issues when you're already in a sub-sub-section. So, perhaps a new environment, or a colored box around these issues? For example, I like how [Hernan and Robins](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/) use boxes for "Technical" or "Fine Point"s.

**Comment by dpritchLibre** [comment]
I like what this issue is trying to accomplish. We should strive for consistency across sections and authors etc., Maybe a good way to do so is to create a catalog of TeX definitions or macros that we require authors to use for these terms.  A few thoughts:

  * I like `remote machine` and `local machine` as generic terms for various platforms
  * Instead of `R GUI` or `R front-end`, I had another thought: how about `R IDE`?  What do you think?
  * Related to the above, when we're talking about just writing code not in the context of submitting commands to the `R` executable, we should just say `editor`.
  * When talking about a general program that understands SSH protocol, I like `SSH client` (note: lowercase).  When talking about the SSH client that is provided through UNC Software Acquisition, maybe we could say `SSH Communications Security SSH Client`?  It's a little verbose, but I can't think of a better way to disambiguate from other SSH clients.  Ideas?
  * While we're at it, maybe we can create a definition or macro for `UNC Software Acquisition`, mostly just out of convenience since we'll probably be using that expression multiple times throughout the document
  * We should just say shell scripting and the shell environment for the general case unless we are mentioning something that is particular to `Bash` or the `TC shell`, etc.

The Hernan and Robins style looks nice, and seems like it might be possible to achieve given a little elbow grease.

**Comment by BarkleyBG** [comment]
Nice!

1. I like it. Let's set up a glossary of terms in the preamble of the document. And let's be sure to make a good reference to where we define them in the main text.
2. I'm unsure but `R IDE` could work
3. sure
4. How about "your `SSH client`" and "The `SSH-SC Client`" where we define The `SSH-SC Client` as The `SSH Communications Security SSH Client`? Shorter, perhaps just as illustrative
5. Perhaps? Depends on necessity
6. Yes, let's use "shell" unless it's specific to Bash or TC etc

All the above are good for the Beta version. Some could probably make it to Alpha, too, of course.

**Comment by dpritchLibre** [comment]
Sounds good!

**Comment by BarkleyBG** [comment]
I like how we've addressed this issue. I know we haven't actually _carried out_ all the changes, but I think that will happen over time. Do you feel comfortable closing this for now?

**Comment by dpritchLibre** [comment]
Hmm.. maybe at some point we should add a `STYLE_GUIDE.md` or `NOMENCLATURE.md` or something of this sort that codifies these points.  But yeah for now lets just close the issue.

**Comment by BarkleyBG** [comment]
I like this idea. Let's keep it open for a minute and think on it. 

Ideally, the study guide would also be found in the main document as well as maybe a markdown file for developers. Or perhaps we could just add something to the `README` to refer developers to `style_guide.tex`, which is `%input{}` into the main document?

**Comment by BarkleyBG** [comment]
We
 - [ ] need to choose what we want the words to be
 - [ ] need to choose whether we want to use the macros or not

**Comment by BarkleyBG** [comment]
@dpritchLibre If I add a glossary item for "Tectia SSH Client", can we call this good and close it?

We haven't implemented a `STYLE_GUIDE.md` or `NOMENCLATURE.md` but maybe that's for another day? Like, next semester? I think we need to focus on "out the door" now, and then later we can go back and focus on "longevity" and passing the stewardship on to the next group.

**Comment by dpritchLibre** [comment]
Sounds good!  I should add that I'm less and less convince that that's actually the name of the software bet let's save that discussion for another day (like next semester)

**Comment by BarkleyBG** [comment]
More reason to put it in the glossary!

**Comment by BarkleyBG** [comment]
@dpritchLibre Is there anything in here that we still need to do? If not, I can close.

**Comment by dpritchLibre** [comment]
Should be good to close
