### ISSUE TITLE
biber issues

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#68]
@dpritchLibre I ran the iss25_refs branch, but I'm seeming to have issues with biber. It could be my setup more than anything else. I think that my issue arises from running biber more than anything.

NB: I can compile the document, just without any bibliographies.

# biber issues

this is my CLI output
```
$ biber cluster_guide
Can't use an undefined value as an ARRAY reference at Biber.pm line 2909.
INFO - This is Biber 0.9.9
INFO - Logfile is 'cluster_guide.blg'
INFO - Reading 'cluster_guide.bcf'
WARN - Warning: Found biblatex control file version 3.4, expected version 1.7
````

Do you think I need to update some of these CTAN packages? i.e. see: https://tex.stackexchange.com/questions/251437/biber-biblatex-problem-use-of-uninitialized-value 

# pdflatex warnings
(an incomplete list)

## References and labels

- LaTeX Warning: Label `sec:SLURM' multiply defined.
- LaTeX Warning: Label `sec:bash-interactive-login-shell' multiply defined.
- LaTeX Warning: Citation 'cygwin_user_guide' on page 12 undefined on input line 148. 
- LaTeX Warning: Reference `sec:file_storage_system' on page 61 undefined on input line 555.

It seems like these are just things we would have to hunt down and fix, if they are in fact issues.

## unknown warning?

```
<chapters/images/shebang-arguments.pdf, id=2165, 432.61626pt x 326.21875pt>
<use chapters/images/shebang-arguments.pdf> [43pdfTeX warning (ext4): destinati
on with the same identifier (name{figure.2.6}) has been already used, duplicate
 ignored
```
I've never seen this before. It seemingly is related with the `n1.pdf` files you added, too? Perhaps this goes away once other problems are fixed.

## bibliography warnings
these are probably related to the biber issues

```
LaTeX Warning: Empty bibliography on input line 2493.
LaTeX Warning: Empty bibliography on input line 114.
LaTeX Warning: Empty bibliography on input line 133.
```
and
```
Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                cluster_guide
(biblatex)                and rerun LaTeX afterwards. 
```

**Comment by dpritchLibre** [comment]
Hey bud. I'm in PA and didn't bring my computer up, which I'm now regretting because I could just send you the bbl file etc to get the ball rolling.

Troubleshooting: the first thing that comes to mind is to make sure that you delete all of the build files from previous compilations before trying to switch to biblatex.  Then run pdflatex, then biber. Hopefully that will help.  If not then try to compile a MWE to make sure your biber/biblatex toolchain is working properly. Look in CONTRIBUTING.md, I listed there the links there that I found to be the best sites to learn biblatex, and there are plenty of examples that you can copy/paste into a file to test with.  If your MWE compiles but the project still doesn't then I guess we'll have to start checking into the version number and so on.

I get those same label warning errors. I think we just have to hunt them down and fix.

I'm not sure about that other warning. It sounds like something I'm doing wrong on my end. When I start going through revision I'll try to start knocking out all of these warnings.

The empty bibliography stuff is likely just a consequence if the biber issues.

**Comment by BarkleyBG** [comment]
FYI, I tried the `make` command in the `latex` directory, and no dice there either. But I think this is because my PC and Perl do not like each other sometimes (see below)

Here's the output:
```
$ make  # try to do everything
latexmk --pdf --silent cluster_guide
latexmk.exe: The Perl script could not be found.
latexmk.exe: Data: scripts/latexmk/perl/latexmk.pl
make: *** [all] Error 1
```

#### Perl
I think we've discussed this before - it's something I'm not particularly interested in working on right now. Perhaps my PC does need an exorcism after all though :-\

**Comment by BarkleyBG** [comment]
BY the way, the `CONTRIBUTING.html` entry is in the `.gitignore` file because I like to convert the `CONTRIBUTING.md` file (that GitHub reads and auto-formats online) into a local html preview.

So, this and the `README.html` entries in `.gitignore` are sorta-useful-ish right now, but they may/will change in the future.

**Comment by dpritchLibre** [comment]
I do the same thing, only I put them in my .git/info/exclude file

**Comment by BarkleyBG** [comment]
oh, I didn't know about that. Way to git good! 

- Should I add these html files to my .git/info/exclude file? 
- or, are both of us excluding the same file? If so, then we should add it to .gitignore, right?

**Comment by dpritchLibre** [comment]
Haha, I just checked the `.gitignore` file and realized that `CONTRIBUTING.html` and `README.html` was already there so I didn't need to personally ignore them.  Yeah what the heck, since it's just the two of us working on this project so far let's just leave them there and I can take them out of my `.git/info/exclude` file.

**Comment by dpritchLibre** [comment]
So when are you back in town / able to sit down and try and get this issue figured out?

**Comment by BarkleyBG** [comment]
WE ARE DOING SO WELL NOW DAVE!!!

**Comment by dpritchLibre** [comment]
As I remember it, we used the MikTeX package manager to update all of your packages, which included the glossaries stuff.  Once we did that horrible, horrible process, then everything started working.  So I can't say for sure what exactly needed to be updated.

**Comment by BarkleyBG** [comment]
good. this stays closed.
