### ISSUE TITLE
New title?

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#73]
1. Statistical Cluster Computing at UNC BIOS
2. Statistical Computing on the UNC Biostatistics cluster
3. Cluster Computing At UNC Biostatistics
4. UNC Biostatistics Guide to Cluster Computing
5. Guide to Cluster Computing at UNC Biostatistics
6. Statistical Computing with Linux at UNC BIOS
7. Cluster computing guide for UNC Biostatistics
8. Cluster computing guide for UNC Biostatisticians
9. UNC Biostatistics Cluster Computing Guide

**Comment by dpritchLibre** [comment]
@BarkleyBG can you turn that into a numbered list so that we can refer to them by number later?  Maybe at some point then we can both rank our 5 favorites in order, and then choose the one with the best combined ranking.  Or something like that.

Can you add the following to the list also, if you think that any are worthy of consideration?
*  Cluster computing guide for UNC Biostatistics
*  Cluster computing guide for UNC Biostatisticians
*  UNC Biostatistics Cluster Computing Guide

**Comment by BarkleyBG** [comment]
I still prefer 
1. Statistical Cluster Computing at UNC BIOS

I think it's a nice combination of official-sounding, specific, loose, and casual. So, it's asking to be taken seriously, but also not promising to teach everything.

**Comment by dpritchLibre** [comment]
I like that one quite a bit also.  Should we make it official???  I do think it should be "Biostatistics", not "BIOS" though.

Gaaahhhh such a big decision!!

**Comment by BarkleyBG** [comment]
Biostatistics it is!

**Comment by BarkleyBG** [comment]
- merge chapter 0 with appendendices
- Bump to v0.4, with the new title and updated chapter 1 and the lstinline, etc
