### ISSUE TITLE
What to call the SSH Windows client provided by Software Acquisition

### ISSUE THREAD

**Issue by dpritchLibre** [BarkleyBG/LCC#85]
Let's open up a dialogue for what to call the usual SSH client for Windows.  Note that there are actually two SSH clients offered by software acquisition: the other one is called SecureCRT.

I'll start a list below like we did for the title.  Why don't you add any suggestions that you have in a comment and we can discuss Monday.
1.  SSH/SFTP Secure Shell Client
2.  SSH/SFTP Secure Shell Client 3.2.9
3.  SSH Communications Security SSH client
4.  SCS Secure Shell Client
4.  Secure Shell Client
5.  Tectia SSH client

Note for comparison that when we are talking about a general client,  we will probably just say "SSH client" (note lowercase _client_)

--------------

Let's also acknowledge that the *full* name is the most ridiculous and redundant name that I have ever heard and it's not really our fault that we're struggling with this:

    SSH Communications Security SSH/SFTP Secure Shell Client

**Comment by BarkleyBG** [comment]
### Proposal: TSSH Client

I was wondering about: `\newacronym{tectia}{TSSH Client}{The Tectia SSH Client}`. Then:

- `\gls{tectia}` is typed, and easy to remember
- Printed to the PDF (in linked form) is `TSSH Client` (or `the TSSH Client`). This seems nice to me because (1) it is clearly related to ssh, and (2) it is clearly different from the ssh protocol 
- The glossary entry will say 
    - `TSSH Client: The Tectia SSH Client is an application that, among other things, can access the cluster via the ssh protocol. There are other clients that can perform these same ssh-based operations (see what we've written about RStudio, Emacs, or shells built-in to Mac or Linux OS's). This is a confusing name, and we admit it; see the company's website if for a possibly further confusing explanation`: https://www.ssh.com/ssh/protocol/).

### Less TSSH Client the better?

The good news is that we can actually write a lot more of this document without talking about that stupid TSSH Client. I mean, with the #84 bash installation and/or RStudio shell, we have a couple of easy/clean/simple ways to get intro Windows users up to speed without actually relying on the TSSH Client. 

### Moving forward

One of the few reasons I like the TSSH Client is the GUI-based sftp file transfer. That's a nice crutch. We could (1) mention this is a benefit of the TSSH Client, and then (2) try never to mention the TSSH Client again. We could effectively never mention it after Chapter 0 (and the installation appendix).

### My vote:

I vote that we choose a name, stick with it, and in version 2.0 (or Beta milestone) we try to rewrite anything that explicitly involves that stupid program and instead focus on using some kind of Bash shell (via MSYS or Cygwin for windows users, installed with Happy Git)

Sound good? Thoughts?

**Comment by dpritchLibre** [comment]
I'm pretty leery about using the name "Tectia", even though admittedly I was the one that suggested it.  My concern is that I can't find anything that actually confirms that is what the program is.  Without confirmation I wouldn't feel comfortable using that name.

If we can get confirmation, that would be ideal because that's way more distinctive than any of the options.

----------------------------

I agree that 98% of the time we can just use the general term "SSH client" without referring to a particular implementation.  You've already explained how to use the client in chapter 0, and we should do a section on using a GUI for file transfers, and outside of those two places we need not mention it again.

**Comment by BarkleyBG** [comment]
What if we gave it a name like "the SSH GUI" or otherwise emphasized the GUIness?

**Comment by BarkleyBG** [comment]
`\newacronym{tectia}{The SCS-SSH client}{The SSH Communications Security SSH client}`

or use the long form instead of the acronym
